In [21]:
comparison = pd.DataFrame({
    'xG': xg_by_team,
    'actual_goals': goals_by_team
})
comparison['diffference'] = comparison['actual_goals'] - comparison['xG'].round(2)
comparison = comparison.sort_values('actual_goals', ascending=False)
print(comparison)

                         xG  actual_goals  diffference
team
Manchester City       64.56            71         6.44
Tottenham Hotspur     62.36            68         5.64
Leicester City        66.28            67         0.72
West Ham United       54.53            64         9.47
Liverpool             58.37            62         3.63
Arsenal               65.14            62        -3.14
Southampton           54.22            57         2.78
Everton               50.61            56         5.39
Chelsea               53.58            55         1.42
Manchester United     42.20            46         3.80
Sunderland            42.49            44         1.51
AFC Bournemouth       40.35            43         2.65
Newcastle United      40.67            43         2.33
Swansea City          42.15            41        -1.15
Stoke City            40.37            40        -0.37
Norwich City          38.89            38        -0.89
Crystal Palace        42.38            38        -4.38
Watford               44.08            36        -8.08
West Bromwich Albion  38.63            32        -6.63
Aston Villa           29.58            25        -4.58

In [19]:
goals_by_team = shots[shots['shot_outcome'] == 'Goal'].groupby('team').size().sort_values(ascending=False)
print(goals_by_team)

team
Manchester City         71
Tottenham Hotspur       68
Leicester City          67
West Ham United         64
Liverpool               62
Arsenal                 62
Southampton             57
Everton                 56
Chelsea                 55
Manchester United       46
Sunderland              44
AFC Bournemouth         43
Newcastle United        43
Swansea City            41
Stoke City              40
Norwich City            38
Crystal Palace          38
Watford                 36
West Bromwich Albion    32
Aston Villa             25
dtype: int64

In [17]:
xg_by_team = shots.groupby('team')['shot_statsbomb_xg'].sum().sort_values(ascending=False).round(2)
print(xg_by_team)

team
Leicester City          66.28
Arsenal                 65.14
Manchester City         64.56
Tottenham Hotspur       62.36
Liverpool               58.37
West Ham United         54.53
Southampton             54.22
Chelsea                 53.58
Everton                 50.61
Watford                 44.08
Sunderland              42.49
Crystal Palace          42.38
Manchester United       42.20
Swansea City            42.15
Newcastle United        40.67
Stoke City              40.37
AFC Bournemouth         40.35
Norwich City            38.89
West Bromwich Albion    38.63
Aston Villa             29.58
Name: shot_statsbomb_xg, dtype: float64

In [16]:
shots = df[df['type'] == 'Shot'].copy()
print(shots.shape)
shots[['player', 'team', 'minute', 'location', 'shot_statsbomb_xg', 'shot_outcome']].head(10)

(9908, 118)

,player,team,minute,location,shot_statsbomb_xg,shot_outcome
3149,Junior Stanislas,AFC Bournemouth,1,"[107.1, 26.6]",0.020838,Blocked
3150,Joshua King,AFC Bournemouth,4,"[113.7, 54.0]",0.034462,Blocked
3151,Riyad Mahrez,Leicester City,9,"[115.7, 50.5]",0.035481,Off T
3152,Joshua King,AFC Bournemouth,13,"[113.9, 38.6]",0.383711,Off T
3153,José Leonardo Ulloa,Leicester City,25,"[96.7, 47.2]",0.036740,Wayward
3154,Jamie Vardy,Leicester City,25,"[111.3, 38.7]",0.575428,Post
3155,Junior Stanislas,AFC Bournemouth,32,"[112.6, 28.7]",0.095998,Off T
3156,José Leonardo Ulloa,Leicester City,33,"[112.1, 32.8]",0.047259,Off T
3157,Dan Gosling,AFC Bournemouth,36,"[108.4, 43.0]",0.256448,Off T
3158,Jamie Vardy,Leicester City,37,"[114.2, 27.2]",0.111973,Wayward

In [15]:
df['type'].value_counts()

type
Pass                 368619
Ball Receipt*        340324
Carry                276949
Pressure             115402
Ball Recovery         40943
Duel                  32290
Clearance             21645
Block                 14839
Dribble               13721
Goal Keeper           11777
Miscontrol            10786
Dispossessed          10520
Shot                   9908
Foul Committed         9512
Foul Won               9112
Interception           8920
Dribbled Past          8771
Substitution           2109
Half Start             1520
Half End               1520
Injury Stoppage        1032
Starting XI             760
Tactical Shift          625
50/50                   559
Shield                  503
Referee Ball-Drop       272
Bad Behaviour           193
Error                   178
Player Off              145
Player On               144
Offside                 109
Own Goal Against         38
Own Goal For             38
Name: count, dtype: int64

In [14]:
df[['type', 'team', 'player', 'minute', 'location', 'match_id']].head(20)

,type,team,player,minute,location,match_id
0,Starting XI,Leicester City,NaN,0,NaN,3754058
1,Starting XI,AFC Bournemouth,NaN,0,NaN,3754058
2,Half Start,AFC Bournemouth,NaN,0,NaN,3754058
3,Half Start,Leicester City,NaN,0,NaN,3754058
4,Half Start,AFC Bournemouth,NaN,45,NaN,3754058
5,Half Start,Leicester City,NaN,45,NaN,3754058
6,Pass,AFC Bournemouth,Dan Gosling,0,"[61.0, 40.1]",3754058
7,Pass,AFC Bournemouth,Joshua King,0,"[60.4, 43.6]",3754058
8,Pass,AFC Bournemouth,Andrew Surman,0,"[48.0, 41.7]",3754058
9,Pass,AFC Bournemouth,Adam Smith,0,"[37.5, 74.6]",3754058
10,Pass,AFC Bournemouth,Simon Francis,0,"[27.4, 63.9]",3754058
11,Pass,AFC Bournemouth,Adam Smith,0,"[30.4, 78.0]",3754058
12,Pass,AFC Bournemouth,Simon Francis,0,"[19.1, 69.7]",3754058
13,Pass,AFC Bournemouth,Steve Cook,0,"[26.4, 25.8]",3754058
14,Pass,AFC Bournemouth,Charlie Daniels,0,"[38.1, 12.1]",3754058
15,Pass,AFC Bournemouth,Steve Cook,0,"[23.4, 27.8]",3754058
16,Pass,AFC Bournemouth,Simon Francis,0,"[36.0, 67.8]",3754058
17,Pass,AFC Bournemouth,Dan Gosling,0,"[49.5, 59.0]",3754058
18,Pass,AFC Bournemouth,Steve Cook,0,"[37.7, 23.5]",3754058
19,Pass,AFC Bournemouth,Charlie Daniels,0,"[57.8, 3.8]",3754058

In [13]:
df.columns.tolist()

['ball_receipt_outcome',
 'ball_recovery_recovery_failure',
 'carry_end_location',
 'clearance_aerial_won',
 'clearance_body_part',
 'clearance_head',
 'clearance_left_foot',
 'clearance_right_foot',
 'counterpress',
 'dribble_nutmeg',
 'dribble_outcome',
 'dribble_overrun',
 'duel_outcome',
 'duel_type',
 'duration',
 'foul_committed_advantage',
 'foul_committed_card',
 'foul_committed_offensive',
 'foul_committed_penalty',
 'foul_committed_type',
 'foul_won_advantage',
 'foul_won_defensive',
 'foul_won_penalty',
 'goalkeeper_body_part',
 'goalkeeper_end_location',
 'goalkeeper_outcome',
 'goalkeeper_position',
 'goalkeeper_punched_out',
 'goalkeeper_technique',
 'goalkeeper_type',
 'id',
 'index',
 'interception_outcome',
 'location',
 'match_id',
 'minute',
 'miscontrol_aerial_won',
 'off_camera',
 'out',
 'pass_aerial_won',
 'pass_angle',
 'pass_assisted_shot_id',
 'pass_body_part',
 'pass_cross',
 'pass_cut_back',
 'pass_deflected',
 'pass_end_location',
 'pass_height',
 'pass_inswinging',
 'pass_length',
 'pass_outcome',
 'pass_outswinging',
 'pass_recipient',
 'pass_recipient_id',
 'pass_shot_assist',
 'pass_switch',
 'pass_technique',
 'pass_through_ball',
 'pass_type',
 'period',
 'play_pattern',
 'player',
 'player_id',
 'position',
 'possession',
 'possession_team',
 'possession_team_id',
 'related_events',
 'second',
 'shot_aerial_won',
 'shot_body_part',
 'shot_end_location',
 'shot_first_time',
 'shot_freeze_frame',
 'shot_key_pass_id',
 'shot_one_on_one',
 'shot_outcome',
 'shot_statsbomb_xg',
 'shot_technique',
 'shot_type',
 'substitution_outcome',
 'substitution_outcome_id',
 'substitution_replacement',
 'substitution_replacement_id',
 'tactics',
 'team',
 'team_id',
 'timestamp',
 'type',
 'under_pressure',
 '50_50',
 'bad_behaviour_card',
 'ball_recovery_offensive',
 'block_offensive',
 'goalkeeper_shot_saved_off_target',
 'shot_open_goal',
 'shot_saved_off_target',
 'goalkeeper_shot_saved_to_post',
 'injury_stoppage_in_chain',
 'pass_goal_assist',
 'pass_straight',
 'pass_no_touch',
 'clearance_other',
 'pass_miscommunication',
 'shot_saved_to_post',
 'block_deflection',
 'dribble_no_touch',
 'shot_redirect',
 'block_save_block',
 'shot_deflected',
 'player_off_permanent',
 'goalkeeper_success_in_play',
 'shot_follows_dribble',
 'goalkeeper_lost_out',
 'half_start_late_video_start',
 'goalkeeper_lost_in_play',
 'goalkeeper_penalty_saved_to_post',
 'goalkeeper_saved_to_post']

In [12]:
df = pd.read_csv('../data/pl_events_raw.csv')
print(df.shape)

/var/folders/28/h_g774gs6rx146htss9pd_b40000gn/T/ipykernel_36533/928287595.py:1: DtypeWarning: Columns (0: dribble_nutmeg, 1: dribble_overrun, 2: foul_committed_card, 3: foul_committed_offensive, 4: foul_committed_penalty, 5: foul_committed_type, 6: foul_won_penalty, 7: goalkeeper_punched_out, 8: miscontrol_aerial_won, 9: pass_cut_back, 10: pass_deflected, 11: pass_outswinging, 12: shot_one_on_one, 13: 50_50, 14: bad_behaviour_card, 15: ball_recovery_offensive, 16: block_offensive, 17: goalkeeper_shot_saved_off_target, 18: shot_open_goal, 19: shot_saved_off_target, 20: goalkeeper_shot_saved_to_post, 21: injury_stoppage_in_chain, 22: pass_goal_assist, 23: pass_straight, 24: pass_no_touch, 25: clearance_other, 26: pass_miscommunication, 27: shot_saved_to_post, 28: block_deflection, 29: dribble_no_touch, 30: shot_redirect, 31: block_save_block, 32: shot_deflected, 33: player_off_permanent, 34: goalkeeper_success_in_play, 35: shot_follows_dribble, 36: goalkeeper_lost_out, 37: half_start_late_video_start, 38: goalkeeper_lost_in_play, 39: goalkeeper_penalty_saved_to_post, 40: goalkeeper_saved_to_post) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('../data/pl_events_raw.csv')

(1313783, 118)

In [11]:
all_events = []
for match_id in matches ['match_id']:
    events = sb.events(match_id=match_id)
    all_events.append(events)

df = pd.concat(all_events, ignore_index=True)
df.to_csv('../data/pl_events_raw.csv', index=False)
print(f"Saved {len(df):,} events")

Saved 1,313,783 events

In [7]:
matches = sb.matches(competition_id=2, season_id=27)

print(f"{len(matches)} matches found")
matches.head()

/Users/oj/Documents/python - learning/football-analytics-dashboard/venv/lib/python3.14/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

380 matches found

,match_id,match_date,kick_off,home_score,away_score,match_status,match_status_360,last_updated,last_updated_360,match_week,competition_id,competition_country_name,competition_name,competition,season_id,season,home_team_id,home_team,home_team_gender,home_team_group,home_team_country_id,home_team_country_name,away_team_id,away_team,away_team_gender,away_team_group,away_team_country_id,away_team_country_name,competition_stage_id,competition_stage,stadium_id,stadium,stadium_country_id,stadium_country_name,referee_id,referee,referee_country_id,referee_country_name,home_managers,away_managers,home_manager_id,home_manager_name,home_manager_nickname,home_manager_dob,home_manager_country_id,home_manager_country_name,away_manager_id,away_manager_name,away_manager_nickname,away_manager_dob,away_manager_country_id,away_manager_country_name,data_version,shot_fidelity_version,xy_fidelity_version
0,3754058,2016-01-02,16:00:00.000,0,0,available,processing,2021-10-29T23:44:19.940296,2021-06-12T16:17:31.694,20,2,England,Premier League,England - Premier League,27,2015/2016,22,Leicester City,male,None,68,England,28,AFC Bournemouth,male,None,68,England,1,Regular Season,20,King Power Stadium,68,England,5,Andre Marriner,68,England,Claudio Ranieri,Eddie Howe,60,Claudio Ranieri,NaN,1951-10-20,112,Italy,38,Eddie Howe,NaN,1977-11-29,68,England,1.1.0,2,2
1,3754245,2015-10-17,16:00:00.000,1,0,available,scheduled,2022-12-01T13:09:17.044015,2021-06-13T16:17:31.694,9,2,England,Premier League,England - Premier League,27,2015/2016,27,West Bromwich Albion,male,None,68,England,41,Sunderland,male,None,68,England,1,Regular Season,33,The Hawthorns,68,England,4,Martin Atkinson,68,England,Tony Pulis,Sam Allardyce,300,Tony Pulis,NaN,1958-01-16,249,Wales,561,Sam Allardyce,NaN,1954-10-19,68,England,1.1.0,2,2
2,3754136,2015-12-19,18:30:00.000,1,1,available,scheduled,2020-11-12T23:48:19.757269,2021-06-13T16:17:31.694,17,2,England,Premier League,England - Premier League,27,2015/2016,37,Newcastle United,male,None,68,England,59,Aston Villa,male,None,68,England,1,Regular Season,4674,St. James'' Park,68,England,4,Martin Atkinson,68,England,Steve McClaren,Rémi Garde,40,Steve McClaren,NaN,1961-05-03,68,England,92,Rémi Garde,NaN,1966-04-03,78,France,1.1.0,2,2
3,3754037,2016-04-30,16:00:00.000,2,1,available,processing,2021-07-07T17:59:57.456,2021-06-12T16:17:31.694,36,2,England,Premier League,England - Premier League,27,2015/2016,29,Everton,male,None,68,England,28,AFC Bournemouth,male,None,68,England,1,Regular Season,12,Goodison Park,68,England,7,Neil Swarbrick,68,England,Roberto Martínez Montoliú,Eddie Howe,263,Roberto Martínez Montoliú,Roberto Martínez,1973-07-13,214,Spain,38,Eddie Howe,NaN,1977-11-29,68,England,1.1.0,2,2
4,3754039,2016-02-13,16:00:00.000,1,2,available,processing,2021-07-25T18:09:51.386,2021-06-12T16:17:31.694,26,2,England,Premier League,England - Premier League,27,2015/2016,31,Crystal Palace,male,None,68,England,23,Watford,male,None,68,England,1,Regular Season,37,Selhurst Park,68,England,9,Robert Madley,68,England,Alan Pardew,Enrique Sánchez Flores,382,Alan Pardew,NaN,1961-07-18,68,England,236,Enrique Sánchez Flores,Quique Sánchez Flores,1965-02-05,214,Spain,1.1.0,2,2

In [6]:
pl = comps[comps['competition_name'] == 'Premier League']

print(pl[['competition_id', 'season_id', 'season_name']].to_string())

    competition_id  season_id season_name
64               2         27   2015/2016
65               2         44   2003/2004

In [4]:
comps = sb.competitions()
print(comps[['competition_name', 'competition_id', 'season_name', 'season_id']].to_string())

           competition_name  competition_id season_name  season_id
0             1. Bundesliga               9   2023/2024        281
1             1. Bundesliga               9   2015/2016         27
2    African Cup of Nations            1267        2023        107
3          Champions League              16   2018/2019          4
4          Champions League              16   2017/2018          1
5          Champions League              16   2016/2017          2
6          Champions League              16   2015/2016         27
7          Champions League              16   2014/2015         26
8          Champions League              16   2013/2014         25
9          Champions League              16   2012/2013         24
10         Champions League              16   2011/2012         23
11         Champions League              16   2010/2011         22
12         Champions League              16   2009/2010         21
13         Champions League              16   2008/2009         41
14         Champions League              16   2006/2007         39
15         Champions League              16   2004/2005         37
16         Champions League              16   2003/2004         44
17         Champions League              16   1999/2000         76
18         Champions League              16   1972/1973        277
19         Champions League              16   1971/1972         71
20         Champions League              16   1970/1971        276
21             Copa America             223        2024        282
22             Copa del Rey              87   1983/1984         84
23             Copa del Rey              87   1982/1983        268
24             Copa del Rey              87   1977/1978        279
25  FA Women's Super League              37   2020/2021         90
26  FA Women's Super League              37   2019/2020         42
27  FA Women's Super League              37   2018/2019          4
28       FIFA U20 World Cup            1470        1979        274
29           FIFA World Cup              43        2022        106
30           FIFA World Cup              43        2018          3
31           FIFA World Cup              43        1990         55
32           FIFA World Cup              43        1986         54
33           FIFA World Cup              43        1974         51
34           FIFA World Cup              43        1970        272
35           FIFA World Cup              43        1962        270
36           FIFA World Cup              43        1958        269
37      Indian Super league            1238   2021/2022        108
38                  La Liga              11   2020/2021         90
39                  La Liga              11   2019/2020         42
40                  La Liga              11   2018/2019          4
41                  La Liga              11   2017/2018          1
42                  La Liga              11   2016/2017          2
43                  La Liga              11   2015/2016         27
44                  La Liga              11   2014/2015         26
45                  La Liga              11   2013/2014         25
46                  La Liga              11   2012/2013         24
47                  La Liga              11   2011/2012         23
48                  La Liga              11   2010/2011         22
49                  La Liga              11   2009/2010         21
50                  La Liga              11   2008/2009         41
51                  La Liga              11   2007/2008         40
52                  La Liga              11   2006/2007         39
53                  La Liga              11   2005/2006         38
54                  La Liga              11   2004/2005         37
55                  La Liga              11   1973/1974        278
56         Liga Profesional              81   1997/1998         48
57         Liga Profesional              81        1981        275
58                  Ligue 1               7   2022/2023        235
59                  Ligue 1               7   2021/2022        108
60                  Ligue 1               7   2015/2016         27
61      Major League Soccer              44        2023        107
62    North American League             116        1977         68
63                     NWSL              49        2018          3
64           Premier League               2   2015/2016         27
65           Premier League               2   2003/2004         44
66                  Serie A              12   2015/2016         27
67                  Serie A              12   1986/1987         86
68                UEFA Euro              55        2024        282
69                UEFA Euro              55        2020         43
70       UEFA Europa League              35   1988/1989         75
71        UEFA Women's Euro              53        2025        315
72        UEFA Women's Euro              53        2022        106
73        Women's World Cup              72        2023        107
74        Women's World Cup              72        2019         30

/Users/oj/Documents/python - learning/football-analytics-dashboard/venv/lib/python3.14/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

In [2]:
from statsbombpy import sb
import pandas as pd

pd.set_option('display.max_columns', None)